# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='repliedto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reddit_id', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('replied_id', models.CharField(max_length=20)),
                ('timest', models.DateTimeField(auto_now_add=True)),
                ('sub', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'repliedto',
            },
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subscribed_to', models.CharField(max_length=80)),
                ('subscriber', models.CharField(max_length=80)),
                ('subreddit', models.CharField(max_length=200)),
                ('subscribe_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
        migrations.AlterUniqueTogether(
            name='subscriptions',
            unique_together=set([('subscribed_to', 'subscriber', 'subreddit')]),
        ),
    ]
